dcs:
  service-bus:
    clients:
      package-events:
        entitiesType: "TOPIC"
        entitiesName: ${TOPIC_NAME}
        subscriptionName: ${TOPIC_SUBSCRIPTION_NAME}
        credentials:
          clientId: ${CLIENT_ID}
          clientSecret: ${CLIENT_SECRET}
          tenantId: ${TENANT_ID}
          fullyQualifiedNamespace: ${SERVICEBUS_QUALIFIED_NAMESPACE}
        contentType: JSON

package-events:
  datasource-type: remote
  job:
    schedule-time: ${JOB_SCHEDULE_TIME}
  service-bus-clients:
    sender: "package-events"